### ISSUE TITLE
How to make a slide with textInput

### ISSUE THREAD

**Issue by niki-ito** [niki-ito/thesis-2022#1]
Hi @[stalgiag](https://github.com/stalgiag). 

I added chapter 0 and 1 to my game. I have a few questions.

1. How does the [code](https://github.com/niki-ito/thesis-2022/tree/main/script) look overall? Are there any major issues? Besides some browser issues, the code seem to be working fine. 
2. We don't have to address this now, but some browser issues include, the index numbers not going back to 0 when the website is simply refreshed. Only if you close the browser entirely and reload it. This is why I think the images do not show the second and third times. (Or maybe it is a different reason)
3. On the second slide of chapter0 (which is blank at the moment), I want to add a textInput slide where the player can write their name and have that name fill the "XXX" in my texts. What is the function you mentioned before that brings up the user's keyboard?

Thank you! I hope I used this Issue's form right. Please let me know if I can make my questions more comprehensive in the future.

**Comment by niki-ito** [comment]
Update: I've found that **the game works best on my computer** in a browser that has been narrowed down to roughly mobile ratio. When I use "inspect" and use the mobile view on my computer browser, there are issues with the mouse click firing twice for each click. **It works the least on mobile phones**. The audio gets weird, the images don't show and the texts don't get cleared.  I hope we can fix these technical issues at some point. But for now, I am adding the assets and focused on completing the game.

**Comment by stalgiag** [comment]
> 1. How does the [code](https://github.com/niki-ito/thesis-2022/tree/main/script) look overall? Are there any major issues? Besides some browser issues, the code seem to be working fine.

On a quick skim, this looks like a great start.

> 2. We don't have to address this now, but some browser issues include, the index numbers not going back to 0 when the website is simply refreshed. Only if you close the browser entirely and reload it. This is why I think the images do not show the second and third times. (Or maybe it is a different reason)

Hm, any stored variables should reset on reload. This might be another issue.

> 3. On the second slide of chapter0 (which is blank at the moment), I want to add a textInput slide where the player can write their name and have that name fill the "XXX" in my texts. What is the function you mentioned before that brings up the user's keyboard?

The[ input HTML form.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input). You can use the [onsubmit](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onsubmit) event to capture the value after a user presses enter. Or you can use [onchange](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onchange) to capture the value as it changes. If it is easier, you can use p5 to make these DOM elements and track their values. Here is[ an example](https://p5js.org/examples/dom-input-and-button.html).

> Thank you! I hope I used this Issue's form right. Please let me know if I can make my questions more comprehensive in the future.

This works well!

**Comment by stalgiag** [comment]
> Update: I've found that **the game works best on my computer** in a browser that has been narrowed down to roughly mobile ratio. When I use "inspect" and use the mobile view on my computer browser, there are issues with the mouse click firing twice for each click. **It works the least on mobile phones**. The audio gets weird, the images don't show and the texts don't get cleared. I hope we can fix these technical issues at some point. But for now, I am adding the assets and focused on completing the game.

This sounds like a potentially complex problem. Let's look at it in a meeting.
