### ISSUE TITLE
Audio Sounds Glitches on Mobile Device

### ISSUE THREAD

**Issue by niki-ito** [niki-ito/thesis-2022#2]
The audio for my game sounds clear on computer browsers but glitches on mobile safari. 

- Making the file sizes smaller did not fix the issue.
(specifically, I took away 90% of the preload images to decrease the file size. This prevented the error of exceeding file size limits.)
- ogg sound files created en error so I changed them back to mp3.

**Comment by stalgiag** [comment]
I don't experience this on my phone so it could be device or OS specific
