### ISSUE TITLE
Total canvas memory use exceeds the maximum limit (256 MB).

### ISSUE THREAD

**Issue by niki-ito** [niki-ito/thesis-2022#3]
When opening the game on mobile safari, certain images do not get displayed because of this error "**Total canvas memory use exceeds the maximum limit (256 MB)**". (The images load fine on desktop)

- I decreased the file size to 50 - 60% (currently showing 15.9MB total, 6MB assets), but it still did not fix the error.
- It does seem like this error is causing the images to glitch.
- Only loading images for chapter0 took away the error.
- Loading both chapter 0 and 1 triggered the error. (This seems like a problem if we are unable to load even one full chapter)

@stalgiag, I think we have to do plan B and load the images in stages.

**Comment by niki-ito** [comment]
Personal Note: 
(The game works fine on my iPad (similar to the desktop), so if nothing works, I can just have the game available on the iPad for gallery viewing with mobile ratio.)

**Comment by stalgiag** [comment]
It seems that [this is a Safari bug.](https://stackoverflow.com/questions/52532614/total-canvas-memory-use-exceeds-the-maximum-limit-safari-12) It appears to leaking memory in a way that no other browser is. I will try to think about a workaround but an iPad is superior for display for now.

**Comment by stalgiag** [comment]
I monitored the memory allocation and it revealed that there is a pretty severe memory leak in Safari. I tried isolating but was unable. See the attached image. Safari sees this as an error with the DOM. The dom creating an instant memory leak of perceived exobytes is pretty unlikely. I think *unfortunately* that this is likely a bug in Safari. You can continue to try to isolate as you go and we can update to new versions of Safari as they surface but for the sake of the deadline it is probably best to continue to work with the tablet.

The good news is it looks and sounds good on my end!

**Comment by niki-ito** [comment]
Thank you @stalgiag! I see. I will work on making my game look presentable on an iPad for now. Did you say that there is an image attached? I am not sure where I can find that. 

I will try to use CSS and figure out how to make the entire content of the website be a fixed aspect ratio. So when the browser is too thin, there will be margin at the top and bottom, and vice versa. And maybe I'll add a gradient background to that.

**Comment by niki-ito** [comment]
Game started having some issues on iPad. No errors in Safari inspector. Sound and button mechanics work but images and text are not visible on first load. Takes a few playing around and refreshing for all the images to appear (then works great). Does it have something to do with the images not being loaded the first time? Please let me know your thoughts @stalgiag

**Comment by niki-ito** [comment]
On the computer, it seems like it works better on firefox. But on the iPad, it's the same and still has issues with showing images the first time.

**Comment by niki-ito** [comment]
@stalgiag since firefox on a desktop works 100% of the time, I might use a desktop to show the game during the exhibition. I realized that if I uncheck "enable touch simulation," it doesn't do the double select error that it has been doing and works perfectly.

**Comment by stalgiag** [comment]
I would hold off on implementing Plan B. It might be complex and I want to do a memory analysis to make sure there isn’t another cause. It is good to know that the iPad can serve as a backup plan. That is probably a superior display anyways.

I’ll follow up once I get a chance to look at the memory problem.
